### ISSUE TITLE
[del] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [johnagan/clean-webpack-plugin#209]
npm warn deprecated rimraf@2.7.1:
Rimraf versions prior to v4 are no longer supported
![del@4 1 1](https://github.com/johnagan/clean-webpack-plugin/assets/531628/4787a939-5408-4e4b-bed8-11ba8ca3b747)

npm warn deprecated glob@7.2.3:
Glob versions prior to v9 are no longer supported
![rimraf@2 7 1](https://github.com/johnagan/clean-webpack-plugin/assets/531628/6020ee2b-2439-4fe4-88d5-33d1a575c669)

**Comment by timmkuehle** [comment]
Unfortunately i can add another, seemingly more serious, deprecation to that:

`npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.`

<details>
<img width="208" alt="error" src="https://github.com/johnagan/clean-webpack-plugin/assets/131286504/b4e8a60f-948e-4f91-a3f4-8f03480875c9">
</details>

@johnagan Since you still have a huge userbase with nearly 2 million downloads per week, it would be much appreciated if you could fix these dependencies. I could also try to tackle this myself and open a PR, but i sadly have very little spare time at the moment and no experience in working with `del` which seems to be the root cause of those dependancy issues.

By the way, you're plugin is still working great in all of the projects that I'm using it in (even with webpack 5 and NodeJS 18) and i assume it also does for many others, so it might be worth the effort. Thanks in advance!

**Comment by johnagan** [comment]
I’d be open to reviewing a PR to address it, but it’s unlikely I’ll have time to resolve this myself.

**Comment by stein2nd** [comment]
For verification, I temporarily modernised package.json by running 'ncu' and 'ncu -u' under the 'clean-webpack-plugin' installation folder.
![@babelpreset-typescript](https://github.com/johnagan/clean-webpack-plugin/assets/531628/7e178ed3-79b4-4c3e-b667-1b21440ea67e)

After running 'npm install --force', several internal modules still show a deprecated warning.

> npm warn deprecated rimraf@3.0.2: 
> Rimraf versions prior to v4 are no longer supported
![temp-sandbox@4 0 1](https://github.com/johnagan/clean-webpack-plugin/assets/531628/fcec2a8d-85f1-45d8-aa43-64f7faf389a5)

> npm warn deprecated glob@7.2.3: 
> Glob versions prior to v9 are no longer supported
![babel-jest@29 7 0](https://github.com/johnagan/clean-webpack-plugin/assets/531628/7b591180-6d1d-44da-8d4c-6aa697389193)

> npm warn deprecated inflight@1.0.6:
> This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
![Pasted Graphic 1](https://github.com/johnagan/clean-webpack-plugin/assets/531628/654cae36-6271-4272-83fb-5480587fef9f)

> npm warn deprecated codecov@3.8.3:
> https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
![Pasted Graphic 5](https://github.com/johnagan/clean-webpack-plugin/assets/531628/25b9da83-d020-4ca4-8e2d-1138d46c5547)

> npm warn deprecated argv@0.0.2:
> Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
![codecov@3 8 3](https://github.com/johnagan/clean-webpack-plugin/assets/531628/64300eb3-6f4e-47fc-a0bc-eb4fd1ec55c7)

**Comment by timmkuehle** [comment]
I'm afraid, I wont be able to solve this issue.

I forked the project and tried to update the `del` dependency manually. When using the updated package in one of my projects, I get an error, telling me I can't use `require()` to import an ESM module:

```
[webpack-cli] Failed to load '~/my-project/Code/webpack.config.js' config
[webpack-cli] Error [ERR_REQUIRE_ESM]: require() of ES Module ~/clean-webpack-plugin/Coding/node_modules/del/index.js from ~/clean-webpack-plugin/Coding/dist/clean-webpack-plugin.js not supported.
Instead change the require of index.js in ~/clean-webpack-plugin/dist/clean-webpack-plugin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (~/clean-webpack-plugin/dist/clean-webpack-plugin.js:7:12)
    at async WebpackCLI.tryRequireThenImport (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:232:34)
    at async loadConfigByPath (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1406:27)
    at async WebpackCLI.loadConfig (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1515:38)
    at async WebpackCLI.createCompiler (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1781:22)
    at async WebpackCLI.runWebpack (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1877:20)
    at async Command.<anonymous> (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:944:21)
    at async Command.parseAsync (~/my-project/Code/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
    at async Command.parseAsync (~/my-project/Code/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async WebpackCLI.run (~/my-project/Code/node_modules/webpack-cli/lib/webpack-cli.js:1360:9)
    at async runCLI (~/my-project/Code/node_modules/webpack-cli/lib/bootstrap.js:9:9) {
  code: 'ERR_REQUIRE_ESM'
}
```

This is caused by the plugin's build system, that transpiles `import` statements into `require()` functions. The updated `del` package does not seem to provide an export that can be used with the `require()` syntax.

Maybe using a dynamic `import()` could fix this, but there seems to be no way to use that synchronously, which in turn disqualifies this as an easy fix.

So I guess, the only option to solve this, would be to adjust the whole build system. Sadly i don't have any experience in using `@babel/cli`, since I always worked with webpack's own cli and I don't really have the time to dig any deeper at this point.

Maybe someone with more experience can help here. Otherwise I think we're stuck with using the plugin in it's current state. This hopefully won't be overly dramatic, since it is only ever used during transpilation and not in production.
