### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by Falieson** [johnagan/clean-webpack-plugin#83]
Following this post: https://github.com/webpack/webpack/issues/6568#issuecomment-377491754
I added `process.traceDeprecation = true` to the top of my webpack.common.js and ran the build again.
The output points to this plugin as causing the warning.

```
clean-webpack-plugin: /Volumes/Vault/Templates/2018-typescript-module/webpack/build has been removed.
  0% compiling(node:83535) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at Object.apply (/Volumes/Vault/Templates/2018-typescript-module/node_modules/write-file-webpack-plugin/dist/index.js:140:14)
    at webpack (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Vault/Templates/2018-typescript-module/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at findNodeScript.then.existing (/Users/<>/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
    at <anonymous>
```

    "clean-webpack-plugin": "0.1.19",

**Comment by Falieson** [comment]
Woops, the package causing the issue is on the following line `write-file-webpack-plugin` . sorry.

**Comment by mlg87** [comment]
in case anyone else finds themselves here, i was getting this error (caused by `clean-webpack-plugin`, not `write-file-webpack-plugin`) bc i was still on `0.1.17`. upgraded to `0.1.19` and got rid of the deprecation warning
